export enum AppRoutes {
  Auth = 'auth',
  Login = 'login',
  Register = 'register',
  // ForgotPassword = 'forgot-password',
  // ResetPassword = 'reset-password',
  // VerifyAccount = 'verify-account',
  Home = 'home',
  // Posts = 'posts',
  // CreatePost = 'create',
  // UpdatePost = 'edit',
  // Profile = 'profile',
  Users = 'users',
  Messanger = 'messanger',
  NotFound = 'not-found',
}
